### PR TITLE
DDP-7342: - changing log4j version

### PR DESCRIPTION
**Pull request by SimoneMaiwald**

### CODE REVIEW

**Comment by SimoneMaiwald** [comment]
```simone@wm598-8c3 ddp-study-manager % mvn dependency:tree
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.broadinstitute.ddp:dsm-backend:jar:SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: javax.xml.bind:jaxb-api:jar -> version 2.3.0 vs 2.3.0-b170201.1204 @ line 232, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.glassfish.jaxb:jaxb-runtime:jar -> version 2.3.2 vs 2.3.0-b170127.1453 @ line 245, column 21
[WARNING] The expression ${build.finalName} is deprecated. Please use ${project.build.finalName} instead.
[WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 9, column 14
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -----------------< org.broadinstitute.ddp:dsm-backend >-----------------
[INFO] Building dsm-backend SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ dsm-backend ---
[INFO] org.broadinstitute.ddp:dsm-backend:jar:SNAPSHOT
[INFO] +- com.sparkjava:spark-core:jar:2.8.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:9.4.12.v20180830:compile
[INFO] |  |  \- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.12.v20180830:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.12.v20180830:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.4.12.v20180830:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-security:jar:9.4.12.v20180830:compile
[INFO] |  +- org.eclipse.jetty.websocket:websocket-server:jar:9.4.12.v20180830:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.12.v20180830:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.4.12.v20180830:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-client:jar:9.4.12.v20180830:compile
[INFO] |  \- org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.12.v20180830:compile
[INFO] |     \- org.eclipse.jetty.websocket:websocket-api:jar:9.4.12.v20180830:compile
[INFO] +- org.broadinstitute.ddp:ldd-backend:jar:dsm_2.4_20200917e:compile
[INFO] |  +- com.google.cloud:google-cloud-storage:jar:1.111.2:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core:jar:1.93.8:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-http:jar:1.93.8:compile
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.36.0:compile
[INFO] |  |  \- com.google.api:gax-httpjson:jar:0.75.2:compile
[INFO] |  +- com.google.cloud:google-cloud-errorreporting:jar:0.120.1-beta:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-error-reporting-v1beta1:jar:0.86.1:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-cloud-error-reporting-v1beta1:jar:0.86.1:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
[INFO] |  |  \- log4j:log4j:jar:1.2.17:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:0.21.1:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.21.1:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.apache.pdfbox:pdfbox:jar:2.0.2:compile
[INFO] |  |  \- org.apache.pdfbox:fontbox:jar:2.0.2:compile
[INFO] |  +- com.typesafe:config:jar:1.3.0:compile
[INFO] |  +- org.zeroturnaround:zt-exec:jar:1.9:compile
[INFO] |  +- com.sendgrid:sendgrid-java:jar:2.2.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpmime:jar:4.3.4:compile
[INFO] |  |  +- org.json:json:jar:20140107:compile
[INFO] |  |  \- com.sendgrid:smtpapi-java:jar:1.2.0:compile
[INFO] |  +- org.apache.httpcomponents:fluent-hc:jar:4.5.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- com.netflix.servo:servo-core:jar:0.8.0:compile
[INFO] |  |  +- com.netflix.servo:servo-internal:jar:0.8.0:compile
[INFO] |  |  \- com.google.code.findbugs:annotations:jar:2.0.0:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  +- com.google.api-client:google-api-client-gson:jar:1.20.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-gson:jar:1.36.0:compile
[INFO] |  +- com.auth0:java-jwt:jar:3.2.0:compile
[INFO] |  +- com.auth0:jwks-rsa:jar:0.2.0:compile
[INFO] |  +- com.google.apis:google-api-services-monitoring:jar:v3-rev5-1.22.0:compile
[INFO] |  +- com.google.apis:google-api-services-storage:jar:v1-rev20200611-1.30.9:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.30.10:compile
[INFO] |  \- com.google.guava:guava:jar:29.0-android:compile
[INFO] +- mysql:mysql-connector-java:jar:8.0.20:compile
[INFO] |  \- com.google.protobuf:protobuf-java:jar:3.13.0:compile
[INFO] +- com.google.cloud.sql:mysql-socket-factory-connector-j-8:jar:1.0.15:compile
[INFO] |  +- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.0.15:compile
[INFO] |  |  \- com.google.apis:google-api-services-sqladmin:jar:v1beta4-rev20190607-1.30.1:compile
[INFO] |  +- com.github.jnr:jnr-unixsocket:jar:0.23:compile
[INFO] |  |  +- com.github.jnr:jnr-ffi:jar:2.1.10:compile
[INFO] |  |  |  +- com.github.jnr:jffi:jar:1.2.19:compile
[INFO] |  |  |  +- com.github.jnr:jffi:jar:native:1.2.19:runtime
[INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:7.1:compile
[INFO] |  |  |  +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |  |  +- com.github.jnr:jnr-constants:jar:0.9.12:compile
[INFO] |  |  +- com.github.jnr:jnr-enxio:jar:0.21:compile
[INFO] |  |  \- com.github.jnr:jnr-posix:jar:3.0.50:compile
[INFO] |  \- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |     \- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] +- com.google.apis:google-api-services-oauth2:jar:v2-rev113-1.22.0:compile
[INFO] +- com.google.cloud:google-cloud-pubsub:jar:1.108.1:compile
[INFO] |  +- io.grpc:grpc-api:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-context:jar:1.31.1:compile
[INFO] |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:runtime
[INFO] |  +- io.grpc:grpc-stub:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-protobuf-lite:jar:1.30.2:compile
[INFO] |  +- com.google.api:api-common:jar:1.10.0:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.18.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:1.90.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-iam-v1:jar:1.0.0:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- com.google.api:gax:jar:1.58.2:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson2:jar:1.36.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.1:compile
[INFO] |  +- com.google.api:gax-grpc:jar:1.58.2:compile
[INFO] |  +- io.grpc:grpc-auth:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-alts:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-grpclb:jar:1.31.1:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.13.0:compile
[INFO] |  +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:compile
[INFO] |  +- org.threeten:threetenbp:jar:1.4.4:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- io.opencensus:opencensus-api:jar:0.24.0:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.31.1:compile
[INFO] |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  +- io.perfmark:perfmark-api:jar:0.19.0:runtime
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.4.0:compile
[INFO] |  +- com.google.auto.value:auto-value-annotations:jar:1.7.2:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.36.0:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  \- io.opencensus:opencensus-contrib-http-util:jar:0.24.0:compile
[INFO] +- com.brsanthu:google-analytics-java:jar:2.0.0:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[INFO] +- org.javalite:activejdbc:jar:1.4.11:compile
[INFO] |  \- org.javalite:javalite-common:jar:1.4.11:compile
[INFO] +- org.apache.commons:commons-dbcp2:jar:2.1.1:compile
[INFO] |  \- org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO] +- org.quartz-scheduler:quartz:jar:2.3.2:compile
[INFO] |  +- com.mchange:c3p0:jar:0.9.5.4:compile
[INFO] |  +- com.mchange:mchange-commons-java:jar:0.2.15:compile
[INFO] |  \- com.zaxxer:HikariCP-java7:jar:2.4.13:compile
[INFO] +- org.quartz-scheduler:quartz-jobs:jar:2.3.2:compile
[INFO] +- com.easypost:easypost-api-client:jar:3.3.3:compile
[INFO] +- com.auth0:auth0:jar:1.2.0:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.7.0:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.12.0:compile
[INFO] |  +- com.squareup.okhttp3:logging-interceptor:jar:3.7.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.8.5:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] +- org.jruby:jruby-complete:jar:9.1.15.0:compile
[INFO] +- org.postgresql:postgresql:jar:42.1.4:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.12:compile
[INFO] +- org.liquibase:liquibase-maven-plugin:jar:3.5.3:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:2.0:compile
[INFO] |  +- org.apache.maven:maven-project:jar:2.0:compile
[INFO] |  |  +- org.apache.maven:maven-profile:jar:2.0:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:2.0:compile
[INFO] |  |  +- org.apache.maven:maven-artifact-manager:jar:2.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-repository-metadata:jar:2.0:compile
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-5:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-utils:jar:1.0.4:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:2.0:compile
[INFO] |  |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8:compile
[INFO] |  |     \- classworlds:classworlds:jar:1.1-alpha-2:compile
[INFO] |  \- org.liquibase:liquibase-core:jar:3.5.3:compile
[INFO] |     \- org.yaml:snakeyaml:jar:1.17:compile
[INFO] +- org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:6.8.2:compile
[INFO] |  +- org.elasticsearch:elasticsearch:jar:6.8.2:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch-core:jar:6.8.2:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch-secure-sm:jar:6.8.2:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch-x-content:jar:6.8.2:compile
[INFO] |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.8.11:compile
[INFO] |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.11:compile
[INFO] |  |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.8.11:compile
[INFO] |  |  +- org.apache.lucene:lucene-core:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-analyzers-common:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-backward-codecs:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-grouping:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-highlighter:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-join:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-memory:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-misc:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queries:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queryparser:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-sandbox:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial-extras:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial3d:jar:7.7.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-suggest:jar:7.7.0:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch-cli:jar:6.8.2:compile
[INFO] |  |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[INFO] |  |  +- com.carrotsearch:hppc:jar:0.7.1:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.10.1:compile
[INFO] |  |  +- com.tdunning:t-digest:jar:3.2:compile
[INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
[INFO] |  |  \- org.elasticsearch:jna:jar:4.5.1:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:6.8.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[INFO] |  +- org.elasticsearch.plugin:parent-join-client:jar:6.8.2:compile
[INFO] |  +- org.elasticsearch.plugin:aggs-matrix-stats-client:jar:6.8.2:compile
[INFO] |  +- org.elasticsearch.plugin:rank-eval-client:jar:6.8.2:compile
[INFO] |  \- org.elasticsearch.plugin:lang-mustache-client:jar:6.8.2:compile
[INFO] |     \- com.github.spullara.mustache.java:compiler:jar:0.9.3:compile
[INFO] +- org.easymock:easymock:jar:3.4:test
[INFO] |  \- org.objenesis:objenesis:jar:2.2:test
[INFO] +- org.mock-server:mockserver-netty:jar:3.10.4:test
[INFO] |  +- org.mock-server:mockserver-client-java:jar:3.10.4:test
[INFO] |  +- org.mock-server:mockserver-core:jar:3.10.4:test
[INFO] |  |  +- io.netty:netty-codec-socks:jar:4.0.34.Final:test
[INFO] |  |  +- com.twitter:finagle-native_2.11:jar:6.33.0:test
[INFO] |  |  |  +- org.scala-lang:scala-library:jar:2.11.7:test
[INFO] |  |  |  +- com.twitter:finagle-core_2.11:jar:6.33.0:test
[INFO] |  |  |  |  +- com.twitter:util-app_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-cache_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-codec_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-collection_2.11:jar:6.32.0:test
[INFO] |  |  |  |  |  +- javax.inject:javax.inject:jar:1:test
[INFO] |  |  |  |  |  \- commons-collections:commons-collections:jar:3.2.1:test
[INFO] |  |  |  |  +- com.twitter:util-core_2.11:jar:6.32.0:test
[INFO] |  |  |  |  |  +- com.twitter:util-function_2.11:jar:6.32.0:test
[INFO] |  |  |  |  |  \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:test
[INFO] |  |  |  |  +- com.twitter:util-hashing_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-jvm_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-lint_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-logging_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-registry_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:util-stats_2.11:jar:6.32.0:test
[INFO] |  |  |  |  +- com.twitter:jsr166e:jar:1.0.0:test
[INFO] |  |  |  |  \- io.netty:netty:jar:3.10.1.Final:test
[INFO] |  |  |  \- com.twitter:finagle-http_2.11:jar:6.33.0:test
[INFO] |  |  |     \- commons-lang:commons-lang:jar:2.6:test
[INFO] |  |  +- com.jcraft:jzlib:jar:1.1.3:test
[INFO] |  |  +- org.bouncycastle:bcmail-jdk15on:jar:1.52:test
[INFO] |  |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.52:test
[INFO] |  |  +- org.skyscreamer:jsonassert:jar:1.2.3:test
[INFO] |  |  \- com.github.fge:json-schema-validator:jar:2.2.6:test
[INFO] |  |     +- com.googlecode.libphonenumber:libphonenumber:jar:6.2:test
[INFO] |  |     +- com.github.fge:json-schema-core:jar:1.2.5:test
[INFO] |  |     |  +- com.github.fge:uri-template:jar:0.9:test
[INFO] |  |     |  |  \- com.github.fge:msg-simple:jar:1.1:test
[INFO] |  |     |  |     \- com.github.fge:btf:jar:1.2:test
[INFO] |  |     |  +- com.github.fge:jackson-coreutils:jar:1.8:test
[INFO] |  |     |  \- org.mozilla:rhino:jar:1.7R4:test
[INFO] |  |     \- javax.mail:mailapi:jar:1.4.3:test
[INFO] |  +- io.netty:netty-buffer:jar:4.0.34.Final:test
[INFO] |  +- io.netty:netty-codec:jar:4.0.34.Final:test
[INFO] |  +- io.netty:netty-codec-http:jar:4.0.34.Final:test
[INFO] |  +- io.netty:netty-common:jar:4.0.34.Final:test
[INFO] |  +- io.netty:netty-handler:jar:4.0.34.Final:test
[INFO] |  +- io.netty:netty-transport:jar:4.0.34.Final:test
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.52:compile
[INFO] |  +- janino:janino:jar:2.5.10:test
[INFO] |  \- org.mock-server:mockserver-logging:jar:3.10.4:test
[INFO] +- org.eclipse.jetty:jetty-servlets:jar:9.4.28.v20200408:compile
[INFO] |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.28.v20200408:compile
[INFO] |  +- org.eclipse.jetty:jetty-http:jar:9.4.28.v20200408:compile
[INFO] |  +- org.eclipse.jetty:jetty-util:jar:9.4.28.v20200408:compile
[INFO] |  \- org.eclipse.jetty:jetty-io:jar:9.4.28.v20200408:compile
[INFO] +- com.aventrix.jnanoid:jnanoid:jar:2.0.0:compile
[INFO] +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] +- xerces:xercesImpl:jar:2.12.1:compile
[INFO] +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453:compile
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.3.0-b170127.1453:compile
[INFO] |  |  \- com.sun.istack:istack-commons-runtime:jar:3.0.4:compile
[INFO] |  +- org.jvnet.staxex:stax-ex:jar:1.7.8:compile
[INFO] |  \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.13:compile
[INFO] +- javax.xml.bind:jaxb-api:jar:2.3.0-b170201.1204:compile
[INFO] +- javax.activation:activation:jar:1.1:compile
[INFO] +- commons-io:commons-io:jar:2.7:compile
[INFO] +- com.google.cloud.functions:functions-framework-api:jar:1.0.1:provided
[INFO] +- com.google.cloud:google-cloud-secretmanager:jar:1.1.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-secretmanager-v1:jar:1.1.1:compile
[INFO] |  \- com.google.api.grpc:proto-google-cloud-secretmanager-v1beta1:jar:1.1.1:compile
[INFO] \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.561 s
[INFO] Finished at: 2021-12-10T14:21:01-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by MocanaAtBroad** [comment]
From the output above, it looks like `ldd-backend` is pulling in an old version of log4j via an slf4j library. I don't know what  `ldd-backend`  is, but it is another thing to correct

**Comment by SimoneMaiwald** [comment]
I think we can ignore the old version ```sgibson  [2:00 PM]
The RASP agent reported it. The super old version is fine, it's not vulnerable. Only 2.0+```

**Review by MocanaAtBroad — APPROVED** [review]
Super-old version of log4j does not appear to be a problem so ✅

**Pull request closed without merging**
